In [1]:
import numpy as np
import pandas as pd
from datetime import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import pandas_datareader as pdr
import os
import talib as tl
from sklearn.preprocessing import LabelBinarizer, StandardScaler
from sklearn_pandas import DataFrameMapper
%matplotlib inline

In [2]:
def fills(df):
    df.fillna(method='ffill', inplace=True)
    df.fillna(method='bfill', inplace=True)
    return df

In [3]:
aapl = fills(pdr.get_data_google('AAPL', '2000-01-01', '2018-01-01'))
spy = fills(pdr.get_data_google('SPY', '2000-01-01', '2018-01-01'))

In [4]:
oopen = aapl['Open'].values
high = aapl['High'].values
low = aapl['Low'].values
close = aapl['Close'].values

In [5]:
runup252 = aapl['Close'].pct_change(252)
aapl['Run Up 252'] = runup252

In [6]:
beta63 = tl.BETA(close, spy['Close'].values, timeperiod=63)
aapl['Beta 63'] = beta63

In [7]:
ema100 = tl.EMA(close, timeperiod=100)
aapl['EMA 100'] = ema100
aapl['EMA 100'] = aapl['EMA 100'].pct_change()

In [8]:
sma100 = tl.SMA(close, timeperiod=100)
aapl['SMA 100'] = sma100
aapl['SMA 100'] = aapl['SMA 100'].pct_change()

In [9]:
sma_mom100 = aapl['SMA 100'] - aapl['SMA 100'].shift(1)
aapl['SMA MOM 100'] = sma_mom100

In [10]:
sp500_sma100 = tl.SMA(spy['Close'].values, timeperiod=100)
aapl['SP500 SMA 100'] = sp500_sma100
aapl['SP500 SMA 100'] = aapl['SP500 SMA 100'].pct_change()

In [11]:
sp500vola = tl.ATR(spy['High'].values, spy['Low'].values, spy['Close'].values, timeperiod=63)
aapl['SP500 Vola 63'] = sp500vola

In [12]:
sharpe_days = 63
daily_ret = aapl['Close'].pct_change()
sharpe63 = np.sqrt(sharpe_days)*(daily_ret.rolling(sharpe_days).mean()/daily_ret.rolling(sharpe_days).std())
aapl['Sharpe 63'] = sharpe63

In [13]:
vola63 = tl.ATR(high, low, close, timeperiod=63)
aapl['Vola 63'] = vola63

In [14]:
return_days = 5
ret = 100*aapl['Close'].pct_change(return_days).shift(-return_days)
aapl[str(return_days) + ' days future return'] = ret

In [15]:
aapl['Weekday'] = aapl.index.dayofweek.map(lambda x: {0: 'Mon', 1: 'Tue', 2: 'Wed', 3: 'Thu', 4: 'Fri'}.get(x))

In [16]:
def to_class(val, extreme):
    if val < -extreme:
        return 'Neg'
    elif val > extreme:
        return 'Pos'
    else:
        return 'Neutral'
aapl['Return class'] = aapl[str(return_days) + ' days future return'].apply(lambda val: to_class(val, 3))
aapl['Return class'].head()

Date
2002-02-11        Neg
2002-02-12        Neg
2002-02-13        Neg
2002-02-14        Neg
2002-02-15    Neutral
Name: Return class, dtype: object

In [17]:
aapl.tail(20)

Open    High     Low   Close    Volume  Run Up 252   Beta 63  \
Date                                                                         
2017-12-01  169.95  171.67  168.50  171.05  39759288    0.562243  0.139494   
2017-12-04  172.48  172.62  169.63  169.80  32542385    0.545041  0.130644   
2017-12-05  169.06  171.52  168.40  169.64  27350154    0.554761  0.132157   
2017-12-06  167.50  170.20  166.46  169.01  28560000    0.537153  0.131991   
2017-12-07  169.03  170.44  168.91  169.32  25673308    0.524993  0.132303   
2017-12-08  170.49  171.00  168.82  169.37  23355231    0.510614  0.115573   
2017-12-11  169.20  172.89  168.79  172.67  35273759    0.515314  0.117088   
2017-12-12  172.15  172.39  171.46  171.70  19409230    0.515446  0.116297   
2017-12-13  172.50  173.54  172.00  172.27  23818447    0.495529  0.115701   
2017-12-14  172.40  173.13  171.65  172.22  20476541    0.495095  0.123054   
2017-12-15  173.63  174.17  172.46  173.97  40169307    0.502072  0.126794   
2017-12-18  174.88  177.20  174.86  176.42  29421114    0.521255  0.132557   
2017-12-19  174.99  175.39  174.09  174.54  27436447    0.496399  0.141924   
2017-12-20  174.87  175.42  173.25  174.35  23475649    0.490808  0.139730   
2017-12-21  174.17  176.02  174.10  175.01  20949896    0.495045  0.141154   
2017-12-22  174.68  175.42  174.50  175.01  16349444    0.504945  0.139007   
2017-12-26  170.80  171.47  169.68  170.57  33185536    0.463869  0.138846   
2017-12-27  170.10  170.78  169.71  170.60  21498213    0.454887  0.137480   
2017-12-28  171.00  171.85  170.48  171.08  16480187    0.465228  0.138857   
2017-12-29  170.52  170.59  169.22  169.23  25999922    0.449756  0.142824   

             EMA 100   SMA 100  SMA MOM 100  SP500 SMA 100  SP500 Vola 63  \
Date                                                                        
2017-12-01  0.001289  0.001582    -0.000066       0.000813       1.436363   
2017-12-04  0.001108  0.001374    -0.000207       0.000784       1.456739   
2017-12-05  0.001066  0.001283    -0.000091       0.000700       1.467108   
2017-12-06  0.000966  0.001210    -0.000073       0.000703       1.460011   
2017-12-07  0.000984  0.001196    -0.000015       0.000730       1.460487   
2017-12-08  0.000970  0.001139    -0.000057       0.000734       1.460955   
2017-12-11  0.001354  0.001385     0.000245       0.000761       1.452051   
2017-12-12  0.001207  0.001327    -0.000058       0.000787       1.445035   
2017-12-13  0.001251  0.001248    -0.000079       0.000788       1.436542   
2017-12-14  0.001218  0.001203    -0.000045       0.000721       1.439454   
2017-12-15  0.001406  0.001265     0.000062       0.000753       1.442796   
2017-12-18  0.001675  0.001593     0.000328       0.000828       1.453069   
2017-12-19  0.001410  0.001540    -0.000053       0.000799       1.452862   
2017-12-20  0.001357  0.001573     0.000033       0.000798       1.455832   
2017-12-21  0.001409  0.001530    -0.000043       0.000797       1.454152   
2017-12-22  0.001379  0.001094    -0.000436       0.000789       1.442816   
2017-12-26  0.000813  0.000917    -0.000177       0.000795       1.429915   
2017-12-27  0.000800  0.000868    -0.000049       0.000782       1.418646   
2017-12-28  0.000841  0.000749    -0.000119       0.000785       1.405652   
2017-12-29  0.000601  0.000558    -0.000191       0.000768       1.413657   

            Sharpe 63   Vola 63  5 days future return Weekday Return class  
Date                                                                        
2017-12-01   0.497874  2.508512             -0.982169     Fri      Neutral  
2017-12-04   0.552009  2.516154              1.690224     Mon      Neutral  
2017-12-05   0.553182  2.525739              1.214336     Tue      Neutral  
2017-12-06   0.556553  2.545013              1.928880     Wed      Neutral  
2017-12-07   0.768109  2.528902              1.712733     Thu      Neutral  
2017-12-08   0.581407  2.523364              2.715947     Fri  

In [18]:
aapl.drop(['Open', 'High', 'Low', 'Close', 'Volume', str(return_days) + ' days future return'], axis=1, inplace=True)
aapl.dropna(inplace=True)

In [19]:
trafos = [([col], StandardScaler()) for col in aapl.columns[:-2].tolist()]
trafos = [('Weekday', LabelBinarizer())] + trafos
#trafos += [('Return class', LabelBinarizer())]

In [24]:
trafos

[('Weekday', LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)),
 (['Run Up 252'], StandardScaler(copy=True, with_mean=True, with_std=True)),
 (['Beta 63'], StandardScaler(copy=True, with_mean=True, with_std=True)),
 (['EMA 100'], StandardScaler(copy=True, with_mean=True, with_std=True)),
 (['SMA 100'], StandardScaler(copy=True, with_mean=True, with_std=True)),
 (['SMA MOM 100'], StandardScaler(copy=True, with_mean=True, with_std=True)),
 (['SP500 SMA 100'], StandardScaler(copy=True, with_mean=True, with_std=True)),
 (['SP500 Vola 63'], StandardScaler(copy=True, with_mean=True, with_std=True)),
 (['Sharpe 63'], StandardScaler(copy=True, with_mean=True, with_std=True)),
 (['Vola 63'], StandardScaler(copy=True, with_mean=True, with_std=True))]

In [25]:
mapper = DataFrameMapper(trafos, df_out=True)

In [26]:
aapl_mapped = mapper.fit_transform(aapl)
aapl_mapped.head()

Weekday_Fri  Weekday_Mon  Weekday_Thu  Weekday_Tue  Weekday_Wed  \
Date                                                                          
2003-02-11          0.0          0.0          0.0          1.0          0.0   
2003-02-12          0.0          0.0          0.0          0.0          1.0   
2003-02-13          0.0          0.0          1.0          0.0          0.0   
2003-02-14          1.0          0.0          0.0          0.0          0.0   
2003-02-18          0.0          0.0          0.0          1.0          0.0   

            Run Up 252   Beta 63   EMA 100   SMA 100  SMA MOM 100  \
Date                                                                
2003-02-11   -1.600356 -0.798219 -1.064351 -0.761711    -0.308494   
2003-02-12   -1.578919 -0.915958 -0.977786 -0.604116     1.227912   
2003-02-13   -1.586341 -0.844042 -0.892677 -0.643545    -0.308234   
2003-02-14   -1.558942 -0.819084 -0.809050 -0.604127     0.306519   
2003-02-18   -1.487150 -0.650059 -0.494465 -0.406947     1.536547   

            SP500 SMA 100  SP500 Vola 63  Sharpe 63   Vola 63  
Date                                                           
2003-02-11      -0.726244       0.437538  -1.152011 -1.292498  
2003-02-12      -0.691979       0.435567  -0.872184 -1.292987  
2003-02-13      -0.586438       0.423277  -1.027448 -1.293269  
2003-02-14      -0.517570       0.412245  -0.924580 -1.293547  
2003-02-18      -0.231390       0.419167  -0.965762 -1.293621

# ML model

In [27]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.grid_search import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.utils import resample

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [28]:
aapl_mapped['Return class'] = aapl['Return class']

### Resample umbalanced data

In [29]:
df_majority = aapl_mapped[aapl_mapped['Return class']=='Neutral']
df_minority = aapl_mapped[aapl_mapped['Return class']!='Neutral']
 
df_minority_upsampled = resample(df_minority, 
                                 replace=True,
                                 n_samples=len(df_majority)*2)

df_upsampled = pd.concat([df_majority, df_minority_upsampled])
 
df_upsampled['Return class'].value_counts()

Pos        2455
Neutral    2002
Neg        1549
Name: Return class, dtype: int64

In [30]:
X = df_upsampled.drop('Return class', axis=1)
y = df_upsampled['Return class']

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [32]:
def fit_and_print(grid):
    grid.fit(X_train, y_train)
    best_estimator = grid.best_estimator_
    print('Best estimator:\n', str(best_estimator))
    
    y_pred = best_estimator.predict(X_test)
    print('Accuracy score:', str(accuracy_score(y_test, y_pred)))
    print('Classification report\n', classification_report(y_test, y_pred))
    print('Confusion matrix\n', str(confusion_matrix(y_test, y_pred)))

### K nearest

In [63]:
params = {'n_neighbors': np.arange(5,50,3),
          'metric': ['euclidean', 'l2', 'manhattan', 'cityblock'],
          'leaf_size': np.arange(5,40,5), 
          'algorithm' : ['auto']}
grid = GridSearchCV(estimator=KNeighborsClassifier(n_jobs=4), param_grid=params)

In [64]:
fit_and_print(grid)

Best estimator:
 KNeighborsClassifier(algorithm='auto', leaf_size=5, metric='manhattan',
           metric_params=None, n_jobs=4, n_neighbors=17, p=2,
           weights='uniform')
Accuracy score: 0.537336024218
Classification report
              precision    recall  f1-score   support

        Neg       0.47      0.44      0.45       508
    Neutral       0.53      0.46      0.49       686
        Pos       0.58      0.67      0.62       788

avg / total       0.53      0.54      0.53      1982

Confusion matrix
 [[223 137 148]
 [134 316 236]
 [122 140 526]]


### Random Forest

In [35]:
params = {'n_estimators': np.arange(20, 40, 2),
          'max_features': [2, 3],
          'min_samples_split': [2, 3],
          'min_samples_leaf': [2, 3, 4]}
grid = GridSearchCV(estimator=RandomForestClassifier(n_jobs=4), param_grid=params)

In [36]:
fit_and_print(grid)

Best estimator:
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=3, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=30, n_jobs=4,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Accuracy score: 0.831987891019
Classification report
              precision    recall  f1-score   support

        Neg       0.86      0.86      0.86       508
    Neutral       0.82      0.69      0.75       686
        Pos       0.82      0.94      0.87       788

avg / total       0.83      0.83      0.83      1982

Confusion matrix
 [[437  60  11]
 [ 62 475 149]
 [  7  44 737]]


# Playground

In [47]:
aapl_temp = fills(pdr.get_data_google('AAPL', '2000-01-01', '2018-01-01'))

In [52]:
aapl_temp['Close'][0:5]

Date
2002-02-11    1.78
2002-02-12    1.76
2002-02-13    1.79
2002-02-14    1.76
2002-02-15    1.71
Name: Close, dtype: float64

In [51]:
aapl_temp['Close'].shift(1)[0:5]

Date
2002-02-11     NaN
2002-02-12    1.78
2002-02-13    1.76
2002-02-14    1.79
2002-02-15    1.76
Name: Close, dtype: float64

In [56]:
aapl_temp['Close'].pct_change(2)[0:5]

Date
2002-02-11         NaN
2002-02-12         NaN
2002-02-13    0.005618
2002-02-14    0.000000
2002-02-15   -0.044693
Name: Close, dtype: float64

In [58]:
aapl_temp['Close'].pct_change(2).shift(-2)[0:5]

Date
2002-02-11    0.005618
2002-02-12    0.000000
2002-02-13   -0.044693
2002-02-14   -0.079545
2002-02-15   -0.035088
Name: Close, dtype: float64